name: crafty_bay
description: "Crafty Bay"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  cupertino_icons: ^1.0.8
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.1
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  http: ^1.5.0
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  flutter_sslcommerz: ^3.0.1
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/

